# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltExam2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='poked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poked_key', to='LogReg.User'),
        ),
        migrations.AlterField(
            model_name='poke',
            name='poker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_key', to='LogReg.User'),
        ),
    ]
